import type { CustomCanvasData } from "./types.js";
import type { Track } from "./timeline-interpolator.js";
import { PARTICLE_PRESETS } from "./particle-system.js";

export interface AnimationPreset {
  id: string;
  name: string;
  description: string;
  duration: number;
  fps: number;
  canvas: CustomCanvasData;
  tracks: Track[];
}

export const DEFAULT_TEMPLATE_VARIABLES: Record<string, string> = {
  userAVTurl: "https://github.com/user-attachments/assets/ebbf178f-a0af-468c-bc6d-34f0502f30a8",
  userName: "ziji",
  guildName: "Hội Vô Danh 2",
};

export const PRESETS: AnimationPreset[] = [
  {
    id: "welcome",
    name: "Welcome Card",
    description: "Avatar pop-in với biến {userName} và {guildName}",
    duration: 1500,
    fps: 12,
    canvas: {
      title: "Welcome Card",
      width: 930,
      height: 280,
      background: "linear-gradient(135deg, #090614 0%, #1e1035 50%, #4a1d6e 100%)",
      elements: [
        {
          id: "avatar",
          type: "avatar",
          x: 36,
          y: 40,
          width: 140,
          height: 140,
          imageUrl: "{userAVTurl}",
          borderRadius: 999,
          border: "4px solid rgba(168, 85, 247, 0.6)",
        },
        {
          id: "title",
          type: "text",
          x: 205,
          y: 55,
          width: 650,
          height: 52,
          content: "Welcome, {userName}!",
          color: "#ffffff",
          fontSize: 44,
          fontWeight: 700,
          textShadow: "0 0 16px rgba(192, 132, 252, 0.75), 2px 3px 6px rgba(0, 0, 0, 0.9)",
          shadowEnabled: true,
          shadowOffsetX: 2,
          shadowOffsetY: 3,
          shadowBlur: 6,
          shadowColor: "rgba(0, 0, 0, 0.9)",
          glowEnabled: true,
          glowBlur: 16,
          glowColor: "#c084fc",
          glowIntensity: "medium",
        },
        {
          id: "subtitle",
          type: "text",
          x: 205,
          y: 115,
          width: 650,
          height: 38,
          content: "Joined {guildName} · Ready for battle",
          color: "#c084fc",
          fontSize: 24,
          fontWeight: 500,
          textShadow: "1px 2px 4px rgba(0, 0, 0, 0.8)",
          shadowEnabled: true,
          shadowOffsetX: 1,
          shadowOffsetY: 2,
          shadowBlur: 4,
          shadowColor: "rgba(0, 0, 0, 0.8)",
        },
        {
          id: "badge",
          type: "badge",
          x: 205,
          y: 175,
          width: 130,
          height: 32,
          content: "✦ NEW MEMBER",
          color: "#ffffff",
          backgroundColor: "#7e22ce",
          borderRadius: 8,
          fontSize: 13,
          textShadow: "0 0 8px rgba(255, 255, 255, 0.5)",
        },
      ],
    },
    tracks: [
      {
        elementId: "avatar",
        keyframes: [
          { id: "av-0", time: 0, x: 20, y: 40, width: 110, height: 110, rotation: -12, scaleX: 0.8, scaleY: 0.8, opacity: 0, easing: "bounce" },
          { id: "av-1", time: 450, x: 36, y: 40, width: 140, height: 140, rotation: 6, scaleX: 1.05, scaleY: 1.05, opacity: 1, easing: "ease-out" },
          { id: "av-2", time: 800, x: 36, y: 40, width: 140, height: 140, rotation: 0, scaleX: 1, scaleY: 1, opacity: 1, easing: "ease-in-out" },
        ],
      },
      {
        elementId: "title",
        keyframes: [
          { id: "ti-0", time: 200, x: 160, y: 55, width: 650, height: 52, rotation: -2, scaleX: 0.95, opacity: 0, easing: "ease-out" },
          { id: "ti-1", time: 650, x: 205, y: 55, width: 650, height: 52, rotation: 0, scaleX: 1, opacity: 1, easing: "ease-in-out" },
        ],
      },
      {
        elementId: "subtitle",
        keyframes: [
          { id: "sub-0", time: 400, x: 170, y: 115, width: 650, height: 38, opacity: 0, easing: "ease-out" },
          { id: "sub-1", time: 850, x: 205, y: 115, width: 650, height: 38, opacity: 1, easing: "ease-in-out" },
        ],
      },
      {
        elementId: "badge",
        keyframes: [
          { id: "bd-0", time: 600, x: 205, y: 195, width: 130, height: 32, rotation: -6, scaleX: 0.85, opacity: 0, easing: "bounce" },
          { id: "bd-1", time: 1050, x: 205, y: 175, width: 130, height: 32, rotation: 0, scaleX: 1, opacity: 1, easing: "ease-in-out" },
        ],
      },
    ],
  },
  {
    id: "cyber-rotation",
    name: "Cyber Dynamic Entrance",
    description: "Multi-axis rotation (-15° -> 10° -> 0°), scaling and cyber glow",
    duration: 1500,
    fps: 15,
    canvas: {
      title: "Holo Cyber Card",
      width: 930,
      height: 280,
      background: "linear-gradient(135deg, #050b14 0%, #0d1b2a 45%, #1b263b 100%)",
      elements: [
        {
          id: "cyber-avatar",
          type: "avatar",
          x: 40,
          y: 40,
          width: 140,
          height: 140,
          imageUrl: "{userAVTurl}",
          borderRadius: 28,
          border: "3px solid #38bdf8",
          rotation: 0,
          scaleX: 1,
          scaleY: 1,
        },
        {
          id: "cyber-title",
          type: "text",
          x: 215,
          y: 50,
          width: 620,
          height: 50,
          content: "OPERATOR: {userName}",
          color: "#38bdf8",
          fontSize: 42,
          fontWeight: 700,
          letterSpacing: 1,
          textShadow: "0 0 16px #0284c7, 0 0 24px #38bdf8",
        },
        {
          id: "cyber-sub",
          type: "text",
          x: 215,
          y: 112,
          width: 620,
          height: 34,
          content: "CYBER CORE ACTIVE · {guildName}",
          color: "#94a3b8",
          fontSize: 22,
          fontWeight: 500,
          letterSpacing: 0.5,
        },
        {
          id: "cyber-tag",
          type: "badge",
          x: 215,
          y: 170,
          width: 160,
          height: 34,
          content: "⚡ ROTATION SYSTEM",
          color: "#0f172a",
          backgroundColor: "#38bdf8",
          borderRadius: 6,
          fontSize: 12,
          fontWeight: 700,
        },
      ],
    },
    tracks: [
      {
        elementId: "cyber-avatar",
        keyframes: [
          { id: "ca-0", time: 0, x: 40, y: 40, width: 140, height: 140, rotation: -18, scaleX: 0.6, scaleY: 0.6, opacity: 0, easing: "bounce" },
          { id: "ca-1", time: 600, x: 40, y: 40, width: 140, height: 140, rotation: 10, scaleX: 1.1, scaleY: 1.1, opacity: 1, easing: "ease-out" },
          { id: "ca-2", time: 1100, x: 40, y: 40, width: 140, height: 140, rotation: 0, scaleX: 1, scaleY: 1, opacity: 1, easing: "ease-in-out" },
        ],
      },
      {
        elementId: "cyber-title",
        keyframes: [
          { id: "ct-0", time: 200, x: 170, y: 50, rotation: -3, scaleX: 0.9, opacity: 0, easing: "ease-out" },
          { id: "ct-1", time: 700, x: 215, y: 50, rotation: 0, scaleX: 1, opacity: 1, easing: "ease-in-out" },
        ],
      },
      {
        elementId: "cyber-tag",
        keyframes: [
          { id: "cg-0", time: 500, x: 215, y: 190, rotation: -10, scaleX: 0.8, opacity: 0, easing: "bounce" },
          { id: "cg-1", time: 900, x: 215, y: 170, rotation: 4, scaleX: 1.05, opacity: 1, easing: "ease-out" },
          { id: "cg-2", time: 1300, x: 215, y: 170, rotation: 0, scaleX: 1, opacity: 1, easing: "ease-in-out" },
        ],
      },
    ],
  },
  {
    id: "music",
    name: "Now Playing Wave",
    description: "Album art pulse and equalizer animation",
    duration: 1600,
    fps: 12,
    canvas: {
      title: "Now Playing Card",
      width: 930,
      height: 280,
      background: "linear-gradient(135deg, #0b0f19 0%, #111827 50%, #064e3b 100%)",
      elements: [
        {
          id: "album",
          type: "image",
          x: 40,
          y: 40,
          width: 140,
          height: 140,
          imageUrl: "{userAVTurl}",
          borderRadius: 20,
          border: "2px solid rgba(52, 211, 153, 0.4)",
        },
        {
          id: "track-title",
          type: "text",
          x: 215,
          y: 50,
          width: 600,
          height: 48,
          content: "Midnight City Lights",
          color: "#ffffff",
          fontSize: 40,
          fontWeight: 700,
          textShadow: "0 0 16px rgba(52, 211, 153, 0.7), 2px 3px 6px rgba(0, 0, 0, 0.85)",
          shadowEnabled: true,
          shadowOffsetX: 2,
          shadowOffsetY: 3,
          shadowBlur: 6,
          shadowColor: "rgba(0, 0, 0, 0.85)",
          glowEnabled: true,
          glowBlur: 16,
          glowColor: "#34d399",
          glowIntensity: "medium",
        },
        {
          id: "artist",
          type: "text",
          x: 215,
          y: 108,
          width: 600,
          height: 32,
          content: "DJ {userName} · {guildName}",
          color: "#6ee7b7",
          fontSize: 22,
          fontWeight: 500,
          textShadow: "1px 2px 4px rgba(0, 0, 0, 0.7)",
          shadowEnabled: true,
          shadowOffsetX: 1,
          shadowOffsetY: 2,
          shadowBlur: 4,
          shadowColor: "rgba(0, 0, 0, 0.7)",
        },
        {
          id: "progress",
          type: "progress",
          x: 215,
          y: 165,
          width: 580,
          height: 14,
          backgroundColor: "rgba(255,255,255,0.1)",
          progressColor: "#10b981",
          progressPercent: 35,
          borderRadius: 999,
        },
      ],
    },
    tracks: [
      {
        elementId: "album",
        keyframes: [
          { id: "alb-0", time: 0, x: 40, y: 40, width: 140, height: 140, opacity: 1, easing: "ease-in-out" },
          { id: "alb-1", time: 800, x: 38, y: 38, width: 144, height: 144, opacity: 1, easing: "ease-in-out" },
          { id: "alb-2", time: 1600, x: 40, y: 40, width: 140, height: 140, opacity: 1, easing: "ease-in-out" },
        ],
      },
      {
        elementId: "progress",
        keyframes: [
          { id: "prg-0", time: 0, width: 580, height: 14, opacity: 1, easing: "linear" },
          { id: "prg-1", time: 1600, width: 580, height: 14, opacity: 1, easing: "linear" },
        ],
      },
    ],
  },
  {
    id: "rank-up",
    name: "Rank Up / XP",
    description: "Level progression and glowing badge pop",
    duration: 1400,
    fps: 12,
    canvas: {
      title: "Level Up Banner",
      width: 930,
      height: 280,
      background: "linear-gradient(135deg, #180d04 0%, #381907 50%, #7c2d12 100%)",
      elements: [
        {
          id: "rank-badge",
          type: "badge",
          x: 45,
          y: 45,
          width: 130,
          height: 130,
          content: "LV. 50",
          color: "#fef08a",
          backgroundColor: "#b45309",
          borderRadius: 30,
          fontSize: 32,
          border: "3px solid #f59e0b",
          textShadow: "0 0 10px rgba(254, 240, 138, 0.7)",
        },
        {
          id: "rank-title",
          type: "text",
          x: 210,
          y: 50,
          width: 600,
          height: 48,
          content: "LEVEL UP: {userName}!",
          color: "#fbbf24",
          fontSize: 38,
          fontWeight: 800,
          textShadow: "0 0 18px rgba(251, 191, 36, 0.8), 2px 3px 6px rgba(0, 0, 0, 0.95)",
          shadowEnabled: true,
          shadowOffsetX: 2,
          shadowOffsetY: 3,
          shadowBlur: 6,
          shadowColor: "rgba(0, 0, 0, 0.95)",
          glowEnabled: true,
          glowBlur: 18,
          glowColor: "#facc15",
          glowIntensity: "medium",
        },
        {
          id: "rank-sub",
          type: "text",
          x: 210,
          y: 110,
          width: 600,
          height: 32,
          content: "XP: 14,850 / 15,000 · {guildName}",
          color: "#fed7aa",
          fontSize: 22,
          fontWeight: 500,
          textShadow: "1px 2px 4px rgba(0, 0, 0, 0.8)",
          shadowEnabled: true,
          shadowOffsetX: 1,
          shadowOffsetY: 2,
          shadowBlur: 4,
          shadowColor: "rgba(0, 0, 0, 0.8)",
        },
        {
          id: "xp-bar",
          type: "progress",
          x: 210,
          y: 165,
          width: 620,
          height: 18,
          backgroundColor: "rgba(0,0,0,0.4)",
          progressColor: "#f59e0b",
          progressPercent: 20,
          borderRadius: 999,
        },
      ],
    },
    tracks: [
      {
        elementId: "rank-badge",
        keyframes: [
          { id: "rb-0", time: 0, x: 45, y: 45, width: 90, height: 90, opacity: 0, easing: "bounce" },
          { id: "rb-1", time: 600, x: 45, y: 45, width: 130, height: 130, opacity: 1, easing: "ease-in-out" },
        ],
      },
      {
        elementId: "rank-title",
        keyframes: [
          { id: "rt-0", time: 200, x: 180, y: 50, opacity: 0, easing: "ease-out" },
          { id: "rt-1", time: 700, x: 210, y: 50, opacity: 1, easing: "ease-in-out" },
        ],
      },
    ],
  },
  {
    id: "spark-magic",
    name: "✨ Spark Magic Banner",
    description: "Hạt lấp lánh vàng kim với hiệu ứng tia lửa rực sáng",
    duration: 1800,
    fps: 15,
    canvas: {
      title: "Spark Magic Card",
      width: 930,
      height: 280,
      background: "linear-gradient(135deg, #0f0728 0%, #1e1145 50%, #2b0b3a 100%)",
      elements: [
        {
          id: "spark-particles",
          type: "particle",
          x: 0,
          y: 0,
          width: 930,
          height: 280,
          zIndex: 1,
          particleConfig: PARTICLE_PRESETS.spark.config,
        },
        {
          id: "avatar",
          type: "avatar",
          x: 40,
          y: 45,
          width: 130,
          height: 130,
          imageUrl: "{userAVTurl}",
          borderRadius: 999,
          border: "4px solid #fbbf24",
          zIndex: 2,
        },
        {
          id: "spark-title",
          type: "text",
          x: 195,
          y: 65,
          width: 680,
          height: 52,
          content: "✨ SPARK OF GLORY: {userName}",
          color: "#fbbf24",
          fontSize: 38,
          fontWeight: 800,
          textShadow: "0 0 20px rgba(251, 191, 36, 0.9), 2px 3px 6px rgba(0, 0, 0, 0.9)",
          zIndex: 3,
        },
        {
          id: "spark-sub",
          type: "text",
          x: 195,
          y: 125,
          width: 680,
          height: 32,
          content: "Empowered by Celestial Starlight · {guildName}",
          color: "#fde68a",
          fontSize: 22,
          fontWeight: 500,
          zIndex: 3,
        },
      ],
    },
    tracks: [
      {
        elementId: "avatar",
        keyframes: [
          { id: "av-0", time: 0, scaleX: 0.8, scaleY: 0.8, opacity: 0, easing: "bounce" },
          { id: "av-1", time: 500, scaleX: 1, scaleY: 1, opacity: 1, easing: "ease-in-out" },
        ],
      },
      {
        elementId: "spark-title",
        keyframes: [
          { id: "st-0", time: 100, y: 80, opacity: 0, easing: "ease-out" },
          { id: "st-1", time: 600, y: 65, opacity: 1, easing: "ease-in-out" },
        ],
      },
    ],
  },
  {
    id: "sakura-petals",
    name: "🌸 Sakura Petals Anime",
    description: "Cánh hoa anh đào lãng mạn bay nhẹ nhàng trong gió",
    duration: 2400,
    fps: 15,
    canvas: {
      title: "Sakura Blossom Banner",
      width: 930,
      height: 280,
      background: "linear-gradient(135deg, #18091e 0%, #2e082d 50%, #4c1135 100%)",
      elements: [
        {
          id: "sakura-particles",
          type: "particle",
          x: 0,
          y: 0,
          width: 930,
          height: 280,
          zIndex: 1,
          particleConfig: PARTICLE_PRESETS.petals.config,
        },
        {
          id: "avatar",
          type: "avatar",
          x: 40,
          y: 45,
          width: 130,
          height: 130,
          imageUrl: "{userAVTurl}",
          borderRadius: 999,
          border: "4px solid #f472b6",
          zIndex: 2,
        },
        {
          id: "sakura-title",
          type: "text",
          x: 195,
          y: 65,
          width: 680,
          height: 52,
          content: "🌸 Sakura Melody · {userName}",
          color: "#fbcfe8",
          fontSize: 38,
          fontWeight: 700,
          textShadow: "0 0 16px rgba(244, 114, 182, 0.85), 2px 2px 4px rgba(0, 0, 0, 0.9)",
          zIndex: 3,
        },
        {
          id: "sakura-sub",
          type: "text",
          x: 195,
          y: 125,
          width: 680,
          height: 32,
          content: "Spring Bloom Edition · {guildName}",
          color: "#f472b6",
          fontSize: 22,
          fontWeight: 500,
          zIndex: 3,
        },
      ],
    },
    tracks: [
      {
        elementId: "sakura-title",
        keyframes: [
          { id: "skt-0", time: 0, opacity: 0, easing: "ease-in" },
          { id: "skt-1", time: 700, opacity: 1, easing: "ease-out" },
        ],
      },
    ],
  },
  {
    id: "music-neon",
    name: "🎵 Music Neon Wave",
    description: "Nốt nhạc bay bổng rực rỡ màu sắc âm nhạc sống động",
    duration: 2000,
    fps: 15,
    canvas: {
      title: "Neon Soundwave Banner",
      width: 930,
      height: 280,
      background: "linear-gradient(135deg, #050616 0%, #0d0c2e 50%, #170733 100%)",
      elements: [
        {
          id: "music-particles",
          type: "particle",
          x: 0,
          y: 0,
          width: 930,
          height: 280,
          zIndex: 1,
          particleConfig: PARTICLE_PRESETS.music.config,
        },
        {
          id: "avatar",
          type: "avatar",
          x: 40,
          y: 45,
          width: 130,
          height: 130,
          imageUrl: "{userAVTurl}",
          borderRadius: 999,
          border: "4px solid #a855f7",
          zIndex: 2,
        },
        {
          id: "music-title",
          type: "text",
          x: 195,
          y: 65,
          width: 680,
          height: 52,
          content: "🎵 NOW PLAYING: {userName}",
          color: "#c084fc",
          fontSize: 38,
          fontWeight: 800,
          textShadow: "0 0 18px rgba(168, 85, 247, 0.9), 2px 3px 6px rgba(0, 0, 0, 0.9)",
          zIndex: 3,
        },
        {
          id: "music-sub",
          type: "text",
          x: 195,
          y: 125,
          width: 680,
          height: 32,
          content: "Volume 100% · Bass Boosted · {guildName}",
          color: "#38bdf8",
          fontSize: 22,
          fontWeight: 500,
          zIndex: 3,
        },
      ],
    },
    tracks: [
      {
        elementId: "music-title",
        keyframes: [
          { id: "mt-0", time: 0, x: 160, opacity: 0, easing: "elastic" },
          { id: "mt-1", time: 700, x: 195, opacity: 1, easing: "ease-out" },
        ],
      },
    ],
  },
];

export function getPresetById(id: string): AnimationPreset | undefined {
  return PRESETS.find((p) => p.id.toLowerCase() === id.toLowerCase());
}
