import type {
  SongResult,
  PresetSample,
  ProfileData,
  LeaderboardData,
  QuoteData,
} from "./types";

export const sampleSongs: SongResult[] = [
  {
    index: 1,
    avatar: "https://i.ytimg.com/vi/jfKfPfyJRdk/hq720.jpg",
    displayName: "lofi hip hop radio - beats to relax/study to",
    time: "3:00:00",
    source: "youtube",
    author: "Chillhop Music",
    views: "24M views",
  },
  {
    index: 2,
    avatar: "https://i.ytimg.com/vi/rUxyKA_-grg/hq720.jpg",
    displayName: "LOFI CHILL MIX (Summer Breeze)",
    time: "1:12:36",
    source: "youtube",
    author: "Dreamy Vibes",
    views: "4.2M views",
  },
  {
    index: 3,
    avatar: "https://i.ytimg.com/vi/5qap5aO4i9A/hq720.jpg",
    displayName: "lofi chill (1 hour deeply relax)",
    time: "1:00:12",
    source: "youtube",
    author: "sleepy cat",
    views: "1.8M views",
  },
  {
    index: 4,
    avatar: "https://i.ytimg.com/vi/DWcJFNfaw9c/hq720.jpg",
    displayName: "Study & Focus Piano Beats",
    time: "02:45:00",
    source: "youtube",
    author: "ChilledCow Studio",
    views: "12.6K likes",
  },
  {
    index: 5,
    avatar: "https://i.ytimg.com/vi/7NOSDKb0HlU/hq720.jpg",
    displayName: "Late Night City Walk - Lofi Beats",
    time: "00:54:20",
    source: "youtube",
    author: "Various Artists",
    views: "8.9K likes",
  },
  {
    index: 6,
    avatar: "https://i.ytimg.com/vi/n61ULEU7SU0/hq720.jpg",
    displayName: "Anime Lofi Memories & Rain",
    time: "00:45:30",
    source: "youtube",
    author: "Ziji Music",
    views: "5.1K likes",
  },
  {
    index: 7,
    avatar: "https://i.ytimg.com/vi/MsHvLrs6sjk/hq720.jpg",
    displayName: "Midnight Coding & Deep Work Beats",
    time: "01:30:15",
    source: "youtube",
    author: "Lofi Girl Studio",
    views: "3.2M views",
  },
  {
    index: 8,
    avatar: "https://i.ytimg.com/vi/ygHUmlIYWe8/hq720.jpg",
    displayName: "Coffee Shop Acoustic & Ambient Rain",
    time: "02:10:00",
    source: "youtube",
    author: "Chill Select",
    views: "950K views",
  },
  {
    index: 9,
    avatar: "https://i.ytimg.com/vi/eC5Mt-CQsk4/hqdefault.jpg",
    displayName: "Tokyo Night Cyberpunk Synth & Chill",
    time: "00:42:18",
    source: "youtube",
    author: "Astral Throb",
    views: "1.1M views",
  },
  {
    index: 10,
    avatar: "https://i.ytimg.com/vi/5d0lbdl58ME/hq720.jpg",
    displayName: "Peaceful Sleep & Meditation Waves",
    time: "08:00:00",
    source: "youtube",
    author: "Zen Atmosphere",
    views: "7.4M views",
  },
  {
    index: 11,
    avatar: "https://i.ytimg.com/vi/vRLSlcuD07U/hq720.jpg",
    displayName: "Warm Sunlight Sunday Morning Vibes",
    time: "00:38:40",
    source: "youtube",
    author: "Sunny Side Beats",
    views: "420K views",
  },
  {
    index: 12,
    avatar: "https://i.ytimg.com/vi/QzYBRb3RgaY/hqdefault.jpg",
    displayName: "Nostalgic Jazzhop in the Attic",
    time: "01:05:22",
    source: "youtube",
    author: "Smooth Jazzhop",
    views: "880K views",
  },
  {
    index: 13,
    avatar: "https://i.ytimg.com/vi/Zeqb_hKkTyY/hq720.jpg",
    displayName: "Rainy Window Aesthetic Lofi Mix",
    time: "01:15:45",
    source: "youtube",
    author: "Ambient Soundscapes",
    views: "2.5M views",
  },
  {
    index: 14,
    avatar: "https://i.ytimg.com/vi/5NVKHu6LzlQ/hq720.jpg",
    displayName: "Retro 80s City Pop Nostalgia",
    time: "00:52:10",
    source: "youtube",
    author: "VaporMemory",
    views: "1.4M views",
  },
  {
    index: 15,
    avatar: "https://i.ytimg.com/vi/k5Xp8Zk4ALY/hq720.jpg",
    displayName: "Ghibli Lofi Inspired Relaxing Sleep",
    time: "02:00:00",
    source: "youtube",
    author: "Spirited Lofi",
    views: "5.8M views",
  },
  {
    index: 16,
    avatar: "https://i.ytimg.com/vi/NRRXrZnhT5s/hq720.jpg",
    displayName: "Autumn Leaves Guitar & Lo-fi Bass",
    time: "00:36:50",
    source: "youtube",
    author: "Acoustic Beats",
    views: "640K views",
  },
  {
    index: 17,
    avatar: "https://i.ytimg.com/vi/jfKfPfyJRdk/hq720.jpg",
    displayName: "Deep Ocean Ambient Waves & Chimes",
    time: "03:15:00",
    source: "youtube",
    author: "Oceanic Sleep",
    views: "3.9M views",
  },
  {
    index: 18,
    avatar: "https://i.ytimg.com/vi/rUxyKA_-grg/hq720.jpg",
    displayName: "Vintage Vinyl Warm Crackle Session",
    time: "01:24:30",
    source: "youtube",
    author: "Dusty Needle Co.",
    views: "710K views",
  },
  {
    index: 19,
    avatar: "https://i.ytimg.com/vi/5qap5aO4i9A/hq720.jpg",
    displayName: "Cloudy Sky Afternoon Dream",
    time: "00:48:15",
    source: "youtube",
    author: "Dream State",
    views: "530K views",
  },
  {
    index: 20,
    avatar: "https://i.ytimg.com/vi/DWcJFNfaw9c/hq720.jpg",
    displayName: "Starry Night Astronomy Lofi Journey",
    time: "02:30:00",
    source: "youtube",
    author: "Cosmic Melodies",
    views: "2.1M views",
  },
];

export const presetSamples: PresetSample[] = [
  {
    id: "sample-20",
    name: "20 tracks (Full Roster)",
    count: 20,
    title: "Lofi & Chill Mega Search (20 Tracks)",
    songs: sampleSongs,
  },
  {
    id: "sample-16",
    name: "16 tracks",
    count: 16,
    title: "Top 16 Trending Beats",
    songs: sampleSongs.slice(0, 16).map((s, idx) => ({ ...s, index: idx + 1 })),
  },
  {
    id: "sample-10",
    name: "10 tracks (Standard)",
    count: 10,
    title: "Top 10 Playlist Results",
    songs: sampleSongs.slice(0, 10).map((s, idx) => ({ ...s, index: idx + 1 })),
  },
  {
    id: "sample-8",
    name: "8 tracks",
    count: 8,
    title: "Essential Study Vibes",
    songs: sampleSongs.slice(0, 8).map((s, idx) => ({ ...s, index: idx + 1 })),
  },
  {
    id: "sample-4",
    name: "4 tracks (Compact)",
    count: 4,
    title: "Top Recommended",
    songs: sampleSongs.slice(0, 4).map((s, idx) => ({ ...s, index: idx + 1 })),
  },
];

export const defaultProfileData: ProfileData = {
  username: "__ziji",
  balance: "13080 xu",
  avatar: "https://i.ytimg.com/vi/MsHvLrs6sjk/hq720.jpg",
  level: 16,
  currentXp: 0,
  requiredXp: 801,
  rank: "#1",
  theme: "ruby-poly",
};

export const defaultLeaderboardData: LeaderboardData = {
  guildName: "Server Leaderboard",
  guildIcon: "https://i.ytimg.com/vi/NRRXrZnhT5s/hq720.jpg",
  items: [
    {
      rank: 1,
      username: "Ziji",
      handle: "@xxxxxxziji",
      avatar: "https://i.ytimg.com/vi/MsHvLrs6sjk/hq720.jpg",
      level: 16,
      xp: 1,
    },
    {
      rank: 2,
      username: "Daniel",
      handle: "@xxxxxd965",
      avatar: "https://i.ytimg.com/vi/ygHUmlIYWe8/hq720.jpg",
      level: 7,
      xp: 120,
    },
    {
      rank: 3,
      username: "deleted_user_b11c1c2d4b",
      handle: "@xxxxx4b07",
      avatar: "https://i.ytimg.com/vi/eC5Mt-CQsk4/hqdefault.jpg",
      level: 6,
      xp: 64,
    },
    {
      rank: 4,
      username: "OHCatarina",
      handle: "@xxxxxxrina",
      avatar: "https://i.ytimg.com/vi/5d0lbdl58ME/hq720.jpg",
      level: 5,
      xp: 88,
    },
    {
      rank: 5,
      username: "JustMox",
      handle: "@xxxxx0432",
      avatar: "https://i.ytimg.com/vi/vRLSlcuD07U/hq720.jpg",
      level: 4,
      xp: 169,
    },
    {
      rank: 6,
      username: "Magnus Dylan",
      handle: "@xxxxx_dai",
      avatar: "https://i.ytimg.com/vi/QzYBRb3RgaY/hqdefault.jpg",
      level: 3,
      xp: 94,
    },
    {
      rank: 7,
      username: "Akimiya",
      handle: "@xxxxxxoang",
      avatar: "https://i.ytimg.com/vi/Zeqb_hKkTyY/hq720.jpg",
      level: 3,
      xp: 92,
    },
    {
      rank: 8,
      username: "gabby_stinks",
      handle: "@xxxxxinks",
      avatar: "https://i.ytimg.com/vi/5NVKHu6LzlQ/hq720.jpg",
      level: 3,
      xp: 86,
    },
    {
      rank: 9,
      username: "knhngc",
      handle: "@xxxxx6125",
      avatar: "https://i.ytimg.com/vi/k5Xp8Zk4ALY/hq720.jpg",
      level: 3,
      xp: 60,
    },
    {
      rank: 10,
      username: "DucGold",
      handle: "@xxxxxxold0",
      avatar: "https://i.ytimg.com/vi/NRRXrZnhT5s/hq720.jpg",
      level: 3,
      xp: 31,
    },
  ],
};

export const defaultQuoteData: QuoteData = {
  quote: "text: Ziji Execute Ziji Execute",
  author: "Ziji",
  handle: "@__ziji",
  tag: "Ziji Execute#9575",
  avatar: "https://i.ytimg.com/vi/MsHvLrs6sjk/hq720.jpg",
};
