import React, { useEffect, useMemo, useRef, useState } from "react";
import type { CustomCanvasData, CustomElement, CustomElementType } from "../lib/types";
import { Code2, Download, Film, ImagePlus, KeyRound, Layers3, Pause, Play, Plus, Trash2, Type, Box, Gauge } from "lucide-react";

type KeyframeProperty = "x" | "y" | "width" | "height" | "opacity";
type Keyframe = { id: string; time: number } & Partial<Record<KeyframeProperty, number>>;
type Track = { elementId: string; keyframes: Keyframe[] };
const clamp = (v: number, min: number, max: number) => Math.max(min, Math.min(max, v));
const lerp = (a: number, b: number, t: number) => a + (b - a) * t;
const ease = (t: number) => t * t * (3 - 2 * t);

const defaultCanvas: CustomCanvasData = { title: "Welcome Card Animation", width: 930, height: 280, background: "linear-gradient(120deg, #090614, #2a1748 55%, #ff9f75)", elements: [
  { id: "title", type: "text", x: 210, y: 72, width: 650, height: 58, content: "Welcome, zijistudio!", color: "#fff", fontSize: 46, fontWeight: 500 },
  { id: "subtitle", type: "text", x: 212, y: 136, width: 600, height: 40, content: "to Hệ Võ Danh 2.", color: "#ddd6fe", fontSize: 28, fontWeight: 400 },
  { id: "avatar", type: "avatar", x: 34, y: 38, width: 148, height: 148, imageUrl: "https://i.ytimg.com/vi/MsHvLrs6sjk/hq720.jpg", borderRadius: 999, border: "3px solid rgba(255,255,255,.35)" },
] };
const defaultTracks: Track[] = [
  { elementId: "title", keyframes: [{ id: "title-0", time: 0, x: 175, y: 72, opacity: 0 }, { id: "title-1", time: 360, x: 210, y: 72, opacity: 1 }] },
  { elementId: "subtitle", keyframes: [{ id: "subtitle-0", time: 240, x: 180, y: 136, opacity: 0 }, { id: "subtitle-1", time: 600, x: 212, y: 136, opacity: 1 }] },
  { elementId: "avatar", keyframes: [{ id: "avatar-0", time: 0, x: 18, y: 38, width: 118, height: 118, opacity: .4 }, { id: "avatar-1", time: 420, x: 34, y: 38, width: 148, height: 148, opacity: 1 }] },
];
function propertyValue(track: Track | undefined, time: number, property: KeyframeProperty, fallback: number) { if (!track?.keyframes.length) return fallback; const frames=[...track.keyframes].sort((a,b)=>a.time-b.time); if(time<=frames[0].time)return frames[0][property]??fallback; if(time>=frames[frames.length-1].time)return frames[frames.length-1][property]??fallback; const i=frames.findIndex(f=>f.time>=time),l=frames[i-1],r=frames[i]; return lerp(l[property]??fallback,r[property]??fallback,ease((time-l.time)/Math.max(1,r.time-l.time))); }
function buildFrame(canvas: CustomCanvasData, tracks: Track[], time: number): CustomCanvasData { return {...canvas,elements:canvas.elements.map(e=>{const t=tracks.find(x=>x.elementId===e.id);return {...e,x:Math.round(propertyValue(t,time,"x",e.x)),y:Math.round(propertyValue(t,time,"y",e.y)),width:Math.round(propertyValue(t,time,"width",e.width)),height:Math.round(propertyValue(t,time,"height",e.height)),opacity:propertyValue(t,time,"opacity",e.opacity??1)};})}; }
function snapshot(e: CustomElement,t: Track,time:number):Keyframe{return{id:`${e.id}-${Math.round(time)}-${Date.now()}`,time:Math.round(time),x:propertyValue(t,time,"x",e.x),y:propertyValue(t,time,"y",e.y),width:propertyValue(t,time,"width",e.width),height:propertyValue(t,time,"height",e.height),opacity:propertyValue(t,time,"opacity",e.opacity??1)};}
const labelFor=(e:CustomElement)=>e.content||e.id;
const elementIcon=(type:CustomElementType)=>type==="text"?<Type className="h-3.5 w-3.5"/>:type==="image"||type==="avatar"?<ImagePlus className="h-3.5 w-3.5"/>:type==="progress"?<Gauge className="h-3.5 w-3.5"/>:<Box className="h-3.5 w-3.5"/>;

export function AnimationTimeline(){
 const [canvas,setCanvas]=useState(defaultCanvas),[tracks,setTracks]=useState(defaultTracks),[duration,setDuration]=useState(1200),[fps,setFps]=useState(10),[format,setFormat]=useState<"gif"|"webp">("gif"),[time,setTime]=useState(360),[playing,setPlaying]=useState(false),[selectedId,setSelectedId]=useState("title"),[selectedKeyframeId,setSelectedKeyframeId]=useState<string|null>("title-1"),[exporting,setExporting]=useState(false); const timelineRef=useRef<HTMLDivElement>(null);
 const frame=useMemo(()=>buildFrame(canvas,tracks,time),[canvas,tracks,time]); const frameCount=Math.ceil(duration/(1000/fps)); const delays=useMemo(()=>Array.from({length:frameCount},()=>Math.round(1000/fps)),[frameCount,fps]); const selectedElement=canvas.elements.find(e=>e.id===selectedId)??canvas.elements[0]; const selectedTrack=tracks.find(t=>t.elementId===selectedId); const selectedKeyframe=selectedTrack?.keyframes.find(k=>k.id===selectedKeyframeId)??null;
 useEffect(()=>{if(!playing)return;const id=window.setInterval(()=>setTime(v=>(v+1000/fps)%duration),1000/fps);return()=>window.clearInterval(id);},[playing,fps,duration]);
 const updateTrack=(id:string,fn:(t:Track)=>Track)=>setTracks(cur=>cur.map(t=>t.elementId===id?fn(t):t)); const select=(id:string,kf:string|null=null)=>{setSelectedId(id);setSelectedKeyframeId(kf)};
 const addKeyframe=(id=selectedId,at=time)=>{const e=canvas.elements.find(x=>x.id===id),t=tracks.find(x=>x.elementId===id);if(!e||!t)return;const existing=t.keyframes.find(k=>Math.abs(k.time-at)<1);if(existing){select(id,existing.id);setTime(existing.time);return}const k=snapshot(e,t,at);updateTrack(id,x=>({...x,keyframes:[...x.keyframes,k].sort((a,b)=>a.time-b.time)}));select(id,k.id);setTime(k.time)};
 const updateKf=(p:KeyframeProperty,v:number)=>{if(!selectedKeyframeId)return;updateTrack(selectedId,t=>({...t,keyframes:t.keyframes.map(k=>k.id===selectedKeyframeId?{...k,[p]:v}:k)}))}; const moveKf=(v:number)=>{if(!selectedKeyframeId)return;const n=Math.round(clamp(v,0,duration));updateTrack(selectedId,t=>({...t,keyframes:t.keyframes.map(k=>k.id===selectedKeyframeId?{...k,time:n}:k).sort((a,b)=>a.time-b.time)}));setTime(n)}; const deleteKf=()=>{if(!selectedKeyframeId||!selectedTrack||selectedTrack.keyframes.length<=1)return;updateTrack(selectedId,t=>({...t,keyframes:t.keyframes.filter(k=>k.id!==selectedKeyframeId)}));setSelectedKeyframeId(null)};
 const moveBar=(id:string,delta:number)=>{const t=tracks.find(x=>x.elementId===id);if(!t?.keyframes.length)return;const min=Math.min(...t.keyframes.map(k=>k.time)),max=Math.max(...t.keyframes.map(k=>k.time)),d=clamp(delta,-min,duration-max);if(!d)return;updateTrack(id,x=>({...x,keyframes:x.keyframes.map(k=>({...k,time:k.time+d}))}));if(selectedId===id)setTime(v=>clamp(v+d,0,duration))};
 const beginBarDrag=(ev:React.PointerEvent<HTMLDivElement>,id:string)=>{const el=timelineRef.current;if(!el)return;ev.preventDefault();const start=ev.clientX,pxPerMs=el.clientWidth/duration;const onMove=(e:PointerEvent)=>moveBar(id,Math.round((e.clientX-start)/Math.max(.001,pxPerMs)));const onUp=()=>{window.removeEventListener("pointermove",onMove);window.removeEventListener("pointerup",onUp)};window.addEventListener("pointermove",onMove);window.addEventListener("pointerup",onUp,{once:true})};
 const addElement=(type:CustomElementType)=>{const id=`${type}-${Date.now()}`;const base:CustomElement={id,type,x:40,y:40,width:type==="text"?360:180,height:type==="text"?48:120,opacity:1,zIndex:canvas.elements.length};if(type==="text")Object.assign(base,{content:"New text",color:"#fff",fontSize:32,fontWeight:500});if(type==="image"||type==="avatar")Object.assign(base,{imageUrl:"",borderRadius:type==="avatar"?999:12});if(type==="badge")Object.assign(base,{content:"Badge",color:"#fff",backgroundColor:"#7c3aed",borderRadius:12,fontSize:18});if(type==="progress")Object.assign(base,{backgroundColor:"#27272a",progressColor:"#a855f7",progressPercent:65,borderRadius:999,height:18});if(type==="box")Object.assign(base,{backgroundColor:"rgba(255,255,255,.08)",borderRadius:16});setCanvas(c=>({...c,elements:[...c.elements,base]}));setTracks(t=>[...t,{elementId:id,keyframes:[{id:`${id}-0`,time:0,x:base.x,y:base.y,width:base.width,height:base.height,opacity:1}]}]);select(id,`${id}-0`)};
 const removeElement=()=>{if(!selectedElement)return;setCanvas(c=>({...c,elements:c.elements.filter(e=>e.id!==selectedId)}));setTracks(t=>t.filter(x=>x.elementId!==selectedId));setSelectedId(canvas.elements.find(e=>e.id!==selectedId)?.id??"");setSelectedKeyframeId(null)};
 const editElement=(patch:Partial<CustomElement>)=>setCanvas(c=>({...c,elements:c.elements.map(e=>e.id===selectedId?{...e,...patch}:e)}));
 const exportAnimation=async()=>{setExporting(true);try{const frames=Array.from({length:frameCount},(_,i)=>buildFrame(canvas,tracks,Math.min(duration-1,Math.round(i*1000/fps))));const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"animated",data:{title:canvas.title,format,frames,delay:delays,loop:0}})});if(!r.ok)throw new Error(await r.text());const blob=await r.blob(),a=document.createElement("a"),url=URL.createObjectURL(blob);a.href=url;a.download=`${canvas.title.replace(/[^a-z0-9]+/gi,"-")}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}finally{setExporting(false)}};
 const copyApi=async()=>navigator.clipboard.writeText(JSON.stringify({type:"animated",data:{title:canvas.title,format,delay:delays,loop:0,frames:Array.from({length:frameCount},(_,i)=>buildFrame(canvas,tracks,Math.min(duration-1,Math.round(i*1000/fps))))}},null,2));
 const fields:Array<[KeyframeProperty,string,number,number,number]>=[["x","X",0,canvas.width,1],["y","Y",0,canvas.height,1],["width","Width",1,canvas.width,1],["height","Height",1,canvas.height,1],["opacity","Opacity",0,1,.01]];
 const input=(label:string,value:any,onChange:(v:string)=>void,type="text")=><label className="block text-[11px] text-slate-400">{label}<input type={type} value={value??""} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-black/30 px-2 py-1.5 text-xs text-slate-100 outline-none focus:border-purple-500/50"/></label>;
 return <div className="min-h-screen bg-[#080612] text-slate-100"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-white/10 bg-[#0c0918]/90 px-5 backdrop-blur-xl"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-tr from-purple-600 via-fuchsia-500 to-indigo-500"><Film className="h-5 w-5"/></div><div><div className="font-semibold">Animation Studio</div><div className="text-[10px] uppercase tracking-[.2em] text-slate-500">Custom Studio timeline</div></div></div><div className="flex gap-2"><select value={format} onChange={e=>setFormat(e.target.value as "gif"|"webp")} className="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs"><option value="gif">GIF</option><option value="webp">Animated WebP</option></select><button onClick={exportAnimation} disabled={exporting} className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 px-4 py-2 text-xs font-semibold"><Download className="h-3.5 w-3.5"/>{exporting?"Rendering…":`Export ${format.toUpperCase()}`}</button></div></header>
 <main className="mx-auto max-w-[1600px] space-y-4 p-4 lg:p-6"><section className="grid gap-4 lg:grid-cols-[1fr_350px]"><div className="rounded-2xl border border-white/10 bg-[#0e0a1e]/80 p-4 shadow-xl"><div className="mb-3 flex justify-between text-xs text-slate-400"><span>Preview · {canvas.width} × {canvas.height}</span><span>{Math.round(time)}ms / {duration}ms</span></div><div className="flex min-h-[360px] items-center justify-center overflow-auto rounded-xl border border-white/10 bg-black/30 p-5"><div className="relative overflow-hidden shadow-2xl" style={{width:canvas.width*.72,height:canvas.height*.72,background:canvas.background}}>{canvas.backgroundImageUrl&&<img src={canvas.backgroundImageUrl} className="absolute inset-0 h-full w-full object-cover"/>}{[...frame.elements].sort((a,b)=>(a.zIndex??0)-(b.zIndex??0)).map(e=><div key={e.id} onClick={()=>select(e.id)} className={`absolute cursor-pointer ${selectedId===e.id?"ring-1 ring-purple-400":""}`} style={{left:e.x*.72,top:e.y*.72,width:e.width*.72,height:e.height*.72,opacity:e.opacity??1}}>{e.type==="text"||e.type==="badge"?<div className="h-full w-full overflow-hidden" style={{color:e.color,background:e.type==="badge"?e.backgroundColor:undefined,borderRadius:e.borderRadius,fontSize:(e.fontSize??24)*.72,fontWeight:e.fontWeight,display:"flex",alignItems:"center",justifyContent:e.textAlign==="center"?"center":e.textAlign==="right"?"flex-end":"flex-start",whiteSpace:"pre-wrap"}}>{e.content}</div>:e.type==="image"||e.type==="avatar"?<img src={e.imageUrl||""} className="h-full w-full object-cover" style={{borderRadius:e.borderRadius,border:e.border}}/>:e.type==="progress"?<div className="h-full w-full" style={{background:e.backgroundColor,borderRadius:e.borderRadius}}><div className="h-full" style={{width:`${e.progressPercent??0}%`,background:e.progressColor,borderRadius:e.borderRadius}}/></div>:<div className="h-full w-full" style={{background:e.backgroundColor,borderRadius:e.borderRadius,border:e.border}}/>}</div>)}</div></div><div className="mt-4 flex items-center gap-3 rounded-xl border border-white/10 bg-black/20 p-3"><button onClick={()=>setPlaying(v=>!v)} className="rounded-lg bg-white/10 p-2">{playing?<Pause className="h-4 w-4"/>:<Play className="h-4 w-4"/>}</button><input type="range" min="0" max={duration} value={time} onChange={e=>setTime(Number(e.target.value))} className="w-full accent-purple-500"/><span className="w-16 text-right font-mono text-xs text-slate-400">{Math.round(time)}ms</span></div></div>
 <aside className="rounded-2xl border border-white/10 bg-[#0e0a1e]/80 p-4 space-y-3"><div className="flex items-center gap-2 text-sm font-semibold"><Layers3 className="h-4 w-4 text-purple-400"/> Elements</div><div className="grid grid-cols-3 gap-1.5">{(["text","image","avatar","badge","progress","box"] as CustomElementType[]).map(type=><button key={type} onClick={()=>addElement(type)} className="flex items-center justify-center gap-1 rounded-lg bg-white/5 p-2 text-[10px]">{elementIcon(type)}{type}</button>)}</div><select value={selectedId} onChange={e=>select(e.target.value)} className="w-full rounded-lg border border-white/10 bg-black/30 px-2 py-2 text-xs">{canvas.elements.map(e=><option key={e.id} value={e.id}>{labelFor(e)} · {e.type}</option>)}</select>{selectedElement&&<><div className="grid grid-cols-2 gap-2">{input("X",selectedElement.x,v=>editElement({x:Number(v)}),"number")}{input("Y",selectedElement.y,v=>editElement({y:Number(v)}),"number")}{input("Width",selectedElement.width,v=>editElement({width:Number(v)}),"number")}{input("Height",selectedElement.height,v=>editElement({height:Number(v)}),"number")}</div>{(selectedElement.type==="text"||selectedElement.type==="badge")&&<><div className="grid grid-cols-2 gap-2">{input("Content",selectedElement.content??"",v=>editElement({content:v}))}{input("Font size",selectedElement.fontSize??24,v=>editElement({fontSize:Number(v)}),"number")}</div>{input("Color",selectedElement.color??"#fff",v=>editElement({color:v}))}</>}{(selectedElement.type==="image"||selectedElement.type==="avatar")&&input("Image URL",selectedElement.imageUrl??"",v=>editElement({imageUrl:v}))}{selectedElement.type==="progress"&&<div className="grid grid-cols-2 gap-2">{input("Percent",selectedElement.progressPercent??0,v=>editElement({progressPercent:clamp(Number(v),0,100)}),"number")}{input("Progress color",selectedElement.progressColor??"#a855f7",v=>editElement({progressColor:v}))}</div>}{selectedElement.type!=="text"&&input("Background",selectedElement.backgroundColor??"",v=>editElement({backgroundColor:v}))}<div className="flex gap-2"><button onClick={()=>addKeyframe()} className="flex flex-1 items-center justify-center gap-1 rounded-lg bg-purple-500/15 px-2 py-2 text-xs"><KeyRound className="h-3 w-3"/>Keyframe</button><button onClick={removeElement} className="rounded-lg border border-red-500/20 bg-red-500/5 px-3 text-red-300"><Trash2 className="h-3.5 w-3.5"/></button></div></>}
 <div className="border-t border-white/10 pt-3"><div className="mb-2 text-xs font-semibold">Animated background</div>{input("GIF / WebP / image URL",canvas.backgroundImageUrl??"",v=>setCanvas(c=>({...c,backgroundImageUrl:v||undefined})))}<div className="mt-2 text-[10px] leading-4 text-slate-500">Animated image backgrounds are sampled per exported frame and embedded into the SVG before GIF/WebP encoding.</div></div><div className="grid grid-cols-2 gap-2 border-t border-white/10 pt-3">{input("Duration",duration,v=>setDuration(clamp(Number(v),120,10000)),"number")}{input("FPS",fps,v=>setFps(clamp(Number(v),2,30)),"number")}</div><button onClick={copyApi} className="flex w-full items-center justify-center gap-2 rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs"><Code2 className="h-3.5 w-3.5"/>Copy API JSON</button></aside></section>
 <section className="overflow-hidden rounded-2xl border border-white/10 bg-[#0e0a1e]/80 shadow-xl"><div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div><div className="text-sm font-semibold">Timeline</div><div className="text-[10px] text-slate-500">Drag ELEMENT bars to move their complete animation · click keyframes to edit</div></div><button onClick={()=>addKeyframe()} className="flex items-center gap-1 rounded-lg bg-white/10 px-3 py-2 text-xs"><Plus className="h-3.5 w-3.5"/>Keyframe</button></div><div className="overflow-x-auto"><div ref={timelineRef} className="min-w-[900px]"><div className="grid grid-cols-[230px_1fr] border-b border-white/5 bg-black/20 text-[10px] text-slate-500"><div className="p-3">ELEMENT</div><div className="relative h-10">{Array.from({length:7},(_,i)=>{const m=Math.round(duration/6*i);return <span key={m} className="absolute top-3 -translate-x-1/2 font-mono" style={{left:`${m/duration*100}%`}}>{m}ms</span>})}</div></div>{canvas.elements.map(e=>{const t=tracks.find(x=>x.elementId===e.id);if(!t)return null;const first=t.keyframes[0]?.time??0,last=t.keyframes.at(-1)?.time??0;return <div key={e.id} className="grid grid-cols-[230px_1fr] border-b border-white/5"><button onClick={()=>select(e.id)} className={`flex items-center gap-2 p-3 text-left text-xs ${selectedId===e.id?"bg-purple-500/10 text-purple-200":"text-slate-300"}`}>{elementIcon(e.type)}<span className="truncate">{labelFor(e)}</span><span className="ml-auto text-[9px] uppercase text-slate-600">{e.type}</span></button><div className="relative h-14 bg-black/10"><div onPointerDown={ev=>beginBarDrag(ev,e.id)} className={`absolute top-4 h-6 cursor-grab rounded-md border ${selectedId===e.id?"border-purple-400/60 bg-purple-500/15":"border-white/10 bg-white/5"}`} style={{left:`${first/duration*100}%`,width:`${Math.max(8,(last-first)/duration*100)}%`}} title="Drag to move all keyframes"/><div className="absolute inset-y-0 w-px bg-purple-400/30 pointer-events-none" style={{left:`${time/duration*100}%`}}/>{t.keyframes.map(k=><button key={k.id} title={`${k.time}ms`} onClick={()=>{select(e.id,k.id);setTime(k.time)}} className={`absolute top-4 z-10 h-6 w-6 -translate-x-1/2 rotate-45 rounded-[5px] border ${selectedKeyframeId===k.id&&selectedId===e.id?"border-purple-200 bg-purple-500 shadow-lg shadow-purple-500/30":"border-purple-500/60 bg-purple-500/30 hover:bg-purple-500/50"}`} style={{left:`${k.time/duration*100}%`}}/>)}</div></div>})}<div className="relative ml-[230px] h-8 border-t border-white/5"><div className="absolute inset-y-0 w-px bg-purple-400" style={{left:`${time/duration*100}%`}}/></div></div></div></section>
 {selectedKeyframe&&<section className="rounded-2xl border border-purple-500/20 bg-purple-500/5 p-4"><div className="mb-3 flex items-center justify-between"><div className="text-sm font-semibold">Keyframe · {Math.round(selectedKeyframe.time)}ms</div><button onClick={deleteKf} className="text-red-300"><Trash2 className="h-4 w-4"/></button></div><div className="grid grid-cols-2 gap-3 md:grid-cols-6">{fields.map(([p,l,min,max,step])=><label key={p} className="text-[11px] text-slate-400">{l}<input type="number" min={min} max={max} step={step} value={Number(selectedKeyframe[p]??0)} onChange={e=>updateKf(p,clamp(Number(e.target.value),min,max))} className="mt-1 w-full rounded-lg border border-white/10 bg-black/30 px-2 py-2 text-xs"/></label>)}<label className="text-[11px] text-slate-400">Time<input type="number" min="0" max={duration} value={selectedKeyframe.time} onChange={e=>moveKf(Number(e.target.value))} className="mt-1 w-full rounded-lg border border-white/10 bg-black/30 px-2 py-2 text-xs"/></label></div></section>}
 </main></div>;
}
